# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: '[{"id": "goshjo", "username": "${{ github.actor }}", "password": "${{ secrets.PESHO }}"}]'
    - name: Build with Maven
      run: cat ~/.m2/settings.xml 
